# Generated by Django 4.2.16 on 2026-05-07 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabapp', '0004_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('app_used', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('place', models.CharField(max_length=200)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('charge_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='cabapp.driver')),
            ],
            options={
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['driver', 'date'], name='cabapp_carc_driver__41aa69_idx')],
            },
        ),
    ]
