# Generated by Django 4.2.16 on 2026-05-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabapp', '0006_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='default_seater',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='driver',
            name='default_vehicle_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
