# Generated by Django 4.2.16 on 2026-05-09 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabapp', '0007_driver_default_seater_driver_default_vehicle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Half', 'Half Day'), ('Full', 'Full Day'), ('Leave', 'Leave'), ('Holiday', 'Holiday')], default='Half', max_length=10),
        ),
        migrations.CreateModel(
            name='AdvanceSalaryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_requests', to='cabapp.driver')),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
    ]
