# Generated by Django 4.2.16 on 2026-05-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabapp', '0008_alter_attendance_status_advancesalaryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='requested_seater',
            field=models.IntegerField(default=4),
        ),
    ]
