# Generated by Django 4.2.16 on 2026-06-29 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabapp', '0009_ride_requested_seater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcharge',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='cabapp.driver'),
        ),
    ]
